#index:
#    path: /
#    controller: App\Controller\DefaultController::index

index:
    path: /
    controller: App\Controller\MainController::indexAction

send-message:
    path: /message/send
    controller: App\Controller\MessageController::sendAction